name: ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: |
          chmod 755 bin/vimpkgsync

      - name: init
        run: |
          bin/vimpkgsync init

      - name: list
        run: |
          bin/vimpkgsync list

      - name: install
        run: |
          bin/vimpkgsync install thinca/vim-quickrun
          bin/vimpkgsync install NLKNguyen/papercolor-theme
          bin/vimpkgsync install branch=center mhinz/vim-startify

      - name: install opt
        run: |
          bin/vimpkgsync install opt itchyny/lightline.vim
          bin/vimpkgsync install opt rbtnn/vim-gloaded
          bin/vimpkgsync install opt branch=visual-mode AndrewRadev/splitjoin.vim

      - name: update
        run: |
          bin/vimpkgsync update

      - name: uninstall
        run: |
          bin/vimpkgsync uninstall NLKNguyen/papercolor-theme
          bin/vimpkgsync uninstall opt itchyny/lightline.vim

      - name: clean
        run: |
          bin/vimpkgsync clean

      - name: list
        run: |
          bin/vimpkgsync list

      - name: help
        run: |
          bin/vimpkgsync help
