name: ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run commands
        run: |
          chmod 755 bin/vimpkgsync
          bin/vimpkgsync init
          bin/vimpkgsync list
          bin/vimpkgsync install thinca/vim-quickrun
          bin/vimpkgsync install NLKNguyen/papercolor-theme
          bin/vimpkgsync install opt itchyny/lightline.vim
          bin/vimpkgsync install opt rbtnn/vim-gloaded
          bin/vimpkgsync update
          bin/vimpkgsync uninstall NLKNguyen/papercolor-theme
          bin/vimpkgsync uninstall opt itchyny/lightline.vim
          bin/vimpkgsync clean
          bin/vimpkgsync list

