name: windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: rhysd/action-setup-vim@v1
      - uses: actions/checkout@v2

      - name: init
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd init

      - name: list
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd list

      - name: install
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd install thinca/vim-quickrun
          call bin\vimpkgsync.cmd install NLKNguyen/papercolor-theme
          call bin\vimpkgsync.cmd install branch=center mhinz/vim-startify

      - name: install opt
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd install opt itchyny/lightline.vim
          call bin\vimpkgsync.cmd install opt rbtnn/vim-gloaded
          call bin\vimpkgsync.cmd install opt branch=visual-mode AndrewRadev/splitjoin.vim

      - name: update
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd update

      - name: uninstall
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd uninstall NLKNguyen/papercolor-theme
          call bin\vimpkgsync.cmd uninstall opt itchyny/lightline.vim

      - name: clean
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd clean

      - name: list
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd list

      - name: help
        shell: cmd
        run: |
          call bin\vimpkgsync.cmd help
